import pathlib, json

p = pathlib.Path(r"C:\Users\sergio\QUANTUMHIVE_ALGORITHMICTRADING\automatizacion\agentes\division_propfirms\agente_gestor_rotacion_cuentas.py")
p.parent.mkdir(parents=True, exist_ok=True)

c = []
c.append('"""Agente Gestor de Rotacion de Cuentas - Division 2B PropFirms')
c.append('Gestion de portafolio con rotacion dinamica, congelamiento por racha,')
c.append('scheduling diario y retiros sistematicos.')
c.append('"""')
c.append('import json')
c.append('import random')
c.append('from datetime import datetime, timezone')
c.append('from pathlib import Path')
c.append('from typing import Any')
c.append('')
c.append('RUTA_RAIZ = Path(__file__).resolve().parents[3]')
c.append("RUTA_PERFILES = RUTA_RAIZ / 'registro' / 'cuentas' / 'perfiles.json'")
c.append("RUTA_HISTORIAL = RUTA_RAIZ / 'registro' / 'cuentas' / 'historial_cuentas.json'")
c.append("RUTA_PLAN = RUTA_RAIZ / 'registro' / 'cuentas' / 'plan_diario.json'")
c.append("RUTA_LOG = RUTA_RAIZ / 'registro' / 'auditoria' / 'gestion_rotacion.jsonl'")
c.append('')
c.append('CONFIG = {')
c.append("    'dias_racha_congelar': 2,")
c.append("    'dias_congelamiento': 2,")
c.append("    'dias_racha_critica': 3,")
c.append("    'dias_congelamiento_critico': 5,")
c.append("    'umbral_retiro_cuenta_pct': 3.0,")
c.append("    'umbral_retiro_portafolio_pct': 3.0,")
c.append("    'max_activas': 5,")
c.append("    'min_activas': 1,")
c.append("    'pct_operan': 0.6,")
c.append('}')
c.append('')
c.append('def _mkdir(ruta):')
c.append('    ruta.parent.mkdir(parents=True, exist_ok=True)')
c.append('')
c.append('def cargar_json(ruta):')
c.append("    if not ruta.exists(): return {}")
c.append("    with open(ruta, 'r', encoding='utf-8') as f:")
c.append('        return json.load(f)')
c.append('')
c.append('def guardar_json(ruta, datos):')
c.append('    _mkdir(ruta)')
c.append("    with open(ruta, 'w', encoding='utf-8') as f:")
c.append('        json.dump(datos, f, indent=2, ensure_ascii=False)')
c.append('')
c.append('def log_jsonl(ruta, entry):')
c.append('    _mkdir(ruta)')
c.append("    with open(ruta, 'a', encoding='utf-8') as f:")
c.append("        f.write(json.dumps(entry, ensure_ascii=False) + '\\n')")
c.append('')
c.append('def racha_perdedora(historial):')
c.append('    dias = 0')
c.append('    for dia in reversed(historial):')
c.append("        if dia.get('pnl_dia', 0) < 0:")
c.append('            dias += 1')
c.append('        else:')
c.append('            break')
c.append('    return dias')
c.append('')
c.append('def metricas_cuenta(historial):')
c.append("    if not historial: return {'win_rate': 0.5, 'pf': 1.0, 'racha': 0, 'dd7': 0.0}")
c.append("    pos = sum(1 for d in historial if d.get('pnl_dia', 0) > 0)")
c.append("    neg = sum(1 for d in historial if d.get('pnl_dia', 0) < 0)")
c.append("    gan = sum(d.get('pnl_dia', 0) for d in historial if d.get('pnl_dia', 0) > 0)")
c.append("    per = abs(sum(d.get('pnl_dia', 0) for d in historial if d.get('pnl_dia', 0) < 0))")
c.append('    ult7 = historial[-7:] if len(historial) > 7 else historial')
c.append("    dd7 = sum(d.get('pnl_dia', 0) for d in ult7 if d.get('pnl_dia', 0) < 0)")
c.append('    return {')
c.append("        'win_rate': round(pos / max(pos + neg, 1), 3),")
c.append("        'pf': round(gan / max(per, 1e-9), 3),")
c.append("        'racha': racha_perdedora(historial),")
c.append("        'dd7': round(dd7, 2),")
c.append('    }')
c.append('')
c.append('def estado_cuenta(cid, m, saldo, inicial):')
c.append('    gan = ((saldo - inicial) / max(inicial, 1)) * 100')
c.append("    if gan >= CONFIG['umbral_retiro_cuenta_pct']:")
c.append("        return 'RETIRO_SUGERIDO', f'Ganancia {gan:.1f}% >= umbral. Proteger capital.'")
c.append("    if m['racha'] >= CONFIG['dias_racha_critica']:")
c.append("        return 'CONGELADA', f'Racha critica {m[chr(39)]racha[chr(39)]} dias. Congelar {CONFIG[chr(39)]dias_congelamiento_critico[chr(39)]} dias.'")
c.append("    if m['racha'] >= CONFIG['dias_racha_congelar']:")
c.append("        return 'CONGELADA', f'Racha {m[chr(39)]racha[chr(39)]} dias. Congelar {CONFIG[chr(39)]dias_congelamiento[chr(39)]} dias.'")
c.append("    return 'ACTIVA', 'Cumple criterios.'")
c.append('')
c.append('def correlacion_signo(hist_a, hist_b):')
c.append('    n = min(len(hist_a), len(hist_b))')
c.append("    if n < 3: return 0.0")
c.append("    sa = [1 if d.get('pnl_dia', 0) >= 0 else -1 for d in hist_a[-n:]]")
c.append("    sb = [1 if d.get('pnl_dia', 0) >= 0 else -1 for d in hist_b[-n:]]")
c.append('    return round(sum(1 for x, y in zip(sa, sb) if x == y) / n, 3)')
c.append('')
c.append('def seleccionar_activas_hoy(estados, metricas, historiales):')
c.append("    activas = [c for c, e in estados.items() if e == 'ACTIVA']")
c.append('    if not activas: return []')
c.append("    max_a = min(CONFIG['max_activas'], max(CONFIG['min_activas'], int(len(activas) * CONFIG['pct_operan'])))\n")
c.append('    scores = {}')
c.append('    for c in activas:')
c.append("        m = metricas[c]")
c.append("        scores[c] = m['win_rate'] * 0.4 + (1 / max(m['pf'], 0.1)) * 0.3 + (1 / max(1 + m['racha'], 1)) * 0.3")
c.append('    seleccionadas = []')
c.append("    candidatos = sorted(activas, key=lambda x: scores[x], reverse=True)")
c.append('    while len(seleccionadas) < max_a and candidatos:')
c.append('        cand = candidatos.pop(0)')
c.append('        alta = False')
c.append('        for s in seleccionadas:')
c.append("            if correlacion_signo(historiales.get(cand, []), historiales.get(s, [])) >= 0.75:")
c.append('                alta = True')
c.append('                break')
c.append('        if not alta:')
c.append('            seleccionadas.append(cand)')
c.append('    return seleccionadas')
c.append('')
c.append('def evaluar_retiro_portafolio(saldos, iniciales):')
c.append('    total_actual = sum(saldos.values())')
c.append('    total_inicial = sum(iniciales.values())')
c.append('    ganancia_pct = ((total_actual - total_inicial) / max(total_inicial, 1)) * 100')
c.append("    return ganancia_pct >= CONFIG['umbral_retiro_portafolio_pct'], ganancia_pct")
c.append('')
c.append('def generar_plan(perfiles, historial):')
c.append('    ahora = datetime.now(timezone.utc).isoformat()')
c.append("    plan = {'fecha': ahora, 'cuentas': {}, 'portafolio': {}, 'justificaciones': {}}")
c.append('    estados = {}')
c.append('    metricas = {}')
c.append('    saldos = {}')
c.append('    iniciales = {}')
c.append('    for cid, p in perfiles.items():')
c.append("        hist = historial.get(cid, [])")
c.append("        saldo = p.get('saldo_actual', 100000.0)")
c.append("        inicial = p.get('saldo_inicial', 100000.0)")
c.append('        saldos[cid] = saldo')
c.append('        iniciales[cid] = inicial')
c.append('        m = metricas_cuenta(hist)')
c.append('        metricas[cid] = m')
c.append('        est, jus = estado_cuenta(cid, m, saldo, inicial)')
c.append('        estados[cid] = est')
c.append("        plan['justificaciones'][cid] = jus")
c.append("        plan['cuentas'][cid] = {'estado': est, 'metricas': m, 'saldo': saldo, 'inicial': inicial}")
c.append('    operan_hoy = seleccionar_activas_hoy(estados, metricas, historial)')
c.append('    for cid in estados:')
c.append("        plan['cuentas'][cid]['opera_hoy'] = (cid in operan_hoy) if estados[cid] == 'ACTIVA' else False")
c.append('    retirar, gan = evaluar_retiro_portafolio(saldos, iniciales)')
c.append("    plan['portafolio'] = {")
c.append("        'capital_total': round(sum(saldos.values()), 2),")
c.append("        'capital_inicial': round(sum(iniciales.values()), 2),")
c.append("        'ganancia_pct': round(gan, 2),")
c.append("        'retiro_sugerido': retirar,")
c.append("        'cuentas_activas': len([c for c, e in estados.items() if e == 'ACTIVA']),")
c.append("        'cuentas_congeladas': len([c for c, e in estados.items() if e == 'CONGELADA']),")
c.append("        'cuentas_retiro': len([c for c, e in estados.items() if e == 'RETIRO_SUGERIDO']),")
c.append("        'cuentas_operan_hoy': operan_hoy,")
c.append('    }')
c.append('    return plan')
c.append('')
c.append('def ejecutar():')
c.append('    perfiles = cargar_json(RUTA_PERFILES)')
c.append("    if not perfiles: raise FileNotFoundError('No hay perfiles. Ejecutar agente_selector_cuenta.py primero.')")
c.append('    historial = cargar_json(RUTA_HISTORIAL)')
c.append('    plan = generar_plan(perfiles, historial)')
c.append('    guardar_json(RUTA_PLAN, plan)')
c.append("    log_jsonl(RUTA_LOG, {'timestamp': plan['fecha'], 'evento': 'plan_diario_generado', 'resumen': plan['portafolio']})")
c.append('    return plan')
c.append('')
c.append('def simular_registro_historial(cuenta_id, fecha_iso, pnl_dia, trades):')
c.append('    historial = cargar_json(RUTA_HISTORIAL)')
c.append("    if cuenta_id not in historial: historial[cuenta_id] = []")
c.append("    historial[cuenta_id].append({'fecha': fecha_iso, 'pnl_dia': pnl_dia, 'trades': trades})")
c.append('    guardar_json(RUTA_HISTORIAL, historial)')
c.append("    log_jsonl(RUTA_LOG, {'timestamp': datetime.now(timezone.utc).isoformat(), 'evento': 'registro_simulado', 'cuenta': cuenta_id, 'pnl_dia': pnl_dia})")
c.append('')
c.append("if __name__ == '__main__':")
c.append('    try:')
c.append('        plan = ejecutar()')
c.append("        print('Plan diario generado:')")
c.append("        print(json.dumps(plan['portafolio'], indent=2, ensure_ascii=False))")
c.append('    except FileNotFoundError as e:')
c.append("        print(f'Error: {e}')")
c.append("        print('Primero ejecutar agente_selector_cuenta.py para crear perfiles.')")

with open(p, 'w', encoding='utf-8') as f:
    f.write('\n'.join(c))
print('Generado', p.stat().st_size)
